// Code generated by __generator__/interpreter.go at once

package builtin

import (
	"testing"

	"github.com/ysugimoto/falco/interpreter/context"
	"github.com/ysugimoto/falco/interpreter/value"
)

// Fastly built-in function testing implementation of digest.base64url_nopad_decode
// Arguments may be:
// - STRING
// Reference: https://developer.fastly.com/reference/vcl/functions/cryptographic/digest-base64url-nopad-decode/
func Test_Digest_base64url_nopad_decode(t *testing.T) {
	t.Run("valid inputs", func(t *testing.T) {
		tests := []struct {
			name   string
			input  string
			expect string
		}{
			{
				name:   "Fastly example",
				input:  "zprOsc67z47PgiDOv8-Bzq_Pg86xz4TOtQ",
				expect: "Καλώς ορίσατε",
			},
			{
				name:   "Includes nullbyte - truncates at null",
				input:  "c29tZSBkYXRhIHdpdGggACBhbmQg77u_",
				expect: "some data with ",
			},
			{
				name:   "Simple decode",
				input:  "YWJjZA",
				expect: "abcd",
			},
			{
				name:   "issue-431",
				input:  "Zm9vYmFyVGVzdAo",
				expect: "foobarTest\n",
			},
		}

		for _, tt := range tests {
			ret, err := Digest_base64url_nopad_decode(
				&context.Context{},
				&value.String{Value: tt.input},
			)

			if err != nil {
				t.Errorf("[%s] Unexpected error: %s", tt.name, err)
			}
			if ret.Type() != value.StringType {
				t.Errorf("[%s] Unexpected return type, expect=STRING, got=%s", tt.name, ret.Type())
			}
			v := value.Unwrap[*value.String](ret)
			if v.Value != tt.expect {
				t.Errorf("[%s] return value unmatch, expect=%s, got=%s", tt.name, tt.expect, v.Value)
			}
		}
	})

	t.Run("invalid inputs return NULL", func(t *testing.T) {
		tests := []struct {
			name  string
			input string
		}{
			{
				name:  "Invalid characters",
				input: "QU&|*#()JDRA",
			},
			{
				name:  "Contains padding (invalid for nopad)",
				input: "YWJjZB==",
			},
			{
				name:  "Contains padding and invalid chars",
				input: "aGVsbG8=0",
			},
		}

		for _, tt := range tests {
			ctx := &context.Context{}
			ret, err := Digest_base64url_nopad_decode(
				ctx,
				&value.String{Value: tt.input},
			)

			if err != nil {
				t.Errorf("[%s] Unexpected error: %s", tt.name, err)
			}
			if ret != value.Null {
				t.Errorf("[%s] Expected NULL for invalid input, got=%s", tt.name, ret.Type())
			}
			if ctx.FastlyError == nil || ctx.FastlyError.Value != "EINVAL" {
				t.Errorf("[%s] Expected FastlyError=EINVAL, got=%v", tt.name, ctx.FastlyError)
			}
		}
	})
}
